import numpy as np
import math
import flint
from typing import Tuple, TypeAlias, List

Vec: TypeAlias = Tuple[int, ...]
Mat: TypeAlias = Tuple[Vec, ...]
Vecs: TypeAlias = List[Vec]


def vec2str(v: Vec) -> str:
    s = ""
    for i, c in enumerate(v):
        i += 1
        if i == len(v):
            s += " + " + str(c)
        elif i == 1:
            s += str(c) + "x" + str(i)
        else:
            s += " + " + str(c) + "x" + str(i)
    return s


def matmul(M: Mat, N: Mat) -> Mat:
    assert len(M[0]) == len(N)
    # Use object dtype (arbitrary-precision Python ints) rather than C long:
    # the KNF quotient module accumulates doubly-exponentially large
    # coefficients on bad variable orders, which overflow int64.
    M = np.array(M, dtype=object)
    N = np.array(N, dtype=object)
    res = M @ N
    return tuple([tuple(int(c) for c in row) for row in res.tolist()])


def affxvars(M: Mat, base: Vec, periods: Vecs) -> Mat:
    # Unpack M into numpy Ax + c
    A = np.array([row[:-1] for row in M], dtype=np.dtype(int))
    c = np.array([row[-1] for row in M], dtype=np.dtype(int))
    # Now, apply the change of variables as
    # Ny + d = A(Py + b) + c = (AP)y + (Ab + c),
    # where P is a matrix with periods as columns
    # and b is the single base
    b = np.array(base, dtype=np.dtype(int))
    d = A @ b + c
    if len(periods) > 0:
        P = np.transpose(np.array(periods, dtype=np.dtype(int)))
        N = A @ P
        # Now put back into the original data-structure types
        N = N.tolist()
        d = d.tolist()
        res = tuple([tuple(row + [d[i]]) for i, row in enumerate(N)])
        return res
    else:  # things are much simpler without periods
        d = d.tolist()
        res = tuple([tuple([c]) for c in d])
        return res


def transpose(M: Mat) -> Mat:
    return tuple([tuple(col) for col in zip(*M)])


def column_style_hnf(M: Mat) -> tuple[Mat, Mat]:
    A = flint.fmpz_mat(M)
    At = A.transpose()
    Ht, Tt = At.hnf(transform=True)
    H = tuple([tuple(r) for r in Ht.transpose().tolist()])
    T = tuple([tuple(r) for r in Tt.transpose().tolist()])
    return (H, T)


def _hnf_colset(gens: Mat) -> frozenset:
    """Canonical set of nonzero HNF basis columns spanning the Z-module
    generated by the rows of `gens`.  Equal Z-modules give equal sets."""
    H, _ = column_style_hnf(transpose(tuple(gens)))
    return frozenset(col for col in transpose(H) if any(c != 0 for c in col))


def in_module(gens: Mat, v: Vec) -> bool:
    """True iff the integer vector `v` lies in the Z-module spanned by the
    rows of `gens`.  Tested by HNF invariance: appending `v` to the
    generators must not change the canonical lattice.

    NOTE: this is the correct membership test for "is g already in Zf+L".
    Comparing literal HNF basis rows (as an earlier version did) is wrong:
    a vector can be in a module without being one of its HNF basis rows,
    which produced spurious non-increasingness witnesses and made the KNF
    search loop on bad orders."""
    gens = tuple(gens)
    if all(c == 0 for c in v):
        return True
    if not gens:
        return False
    return _hnf_colset(gens) == _hnf_colset(gens + (tuple(v),))


def basis_of_ker(M: Mat) -> Mat:
    A = flint.fmpz_mat(M)
    X, nullity = A.nullspace()
    B = tuple([tuple(r[:nullity]) for i, r in enumerate(X.tolist())])
    # NOTE: the basis is not necessarily minimal, i.e. some columns may have
    # nontrivial GCD! so we have to do an extra step to output a reduced basis
    Bt = transpose(B)
    minB = []
    for row in Bt:
        d = math.gcd(*row)
        if d == 0:
            minB.append(row)
        else:
            minB.append(tuple([(c / math.gcd(*row)) for c in row]))
    B = transpose(tuple(minB))
    return B
